name: ${project.name}
main: studio.magemonkey.fusion.Fusion
authors: [ Travja, goflish ]
version: ${project.version}
libraries: [ com.mysql:mysql-connector-j:${mysql.version}, org.apache.commons:commons-lang3:${apache.version} ]
depend:
  - CodexCore
softdepend:
  - AuraSkills
  - AureliumSkills
  - Divinity
  - Fabled
  - Jobs
  - Nexo
  - Sapphire
  - mcMMO
api-version: 1.13
commands:
  craft:
  fusion-editor: